In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

 Dataset Acquisition and Description - CA2A - Cillian Murphy x Philip Kelly - ________________ x D00266046

Our dataset is called 'MER Opportunity and Spirit Rovers Pancam Images Labeled Data Set' taken from - https://zenodo.org/records/4302760.
It is based on 3004 iages collected by Pancam instruments which are mounted of the Opportunity and spirit rovers from the NASA Mars Exploration  Rovers Mission.

There were 25 classes of both scientific and engineering interests.

In [14]:
# Read in text files with the filenames and labels 
def read_txt_files(path):

    rows = []

    with open(path, encoding='UTF-8') as f:
        for line in f:

            line = line.strip()

            filename = line.split(",")[0]

            features = line.split(",")[1:]

            rows.append({'filename':filename, 'features':features})

        data = pd.DataFrame(rows)

        return data

test_data = read_txt_files('rover_image_classification/mer-labeled-data-set-v1.1.0/test-set-v1.1.0.txt')

train_data = read_txt_files('rover_image_classification/mer-labeled-data-set-v1.1.0/train-set-v1.1.0.txt')

val_data = read_txt_files('rover_image_classification/mer-labeled-data-set-v1.1.0/val-set-v1.1.0.txt')

In [15]:
test_data.head()

,filename,features
0,1p128368623mrd0200p2217l2m1.img.jpg,"[ Dunes/Ripples, Soil, Distant Vista, Sky]"
1,1p128369364mrd0200p2217l2m1.img.jpg,"[ Clasts, Soil, Nearby Surface]"
2,1p128369598mrd0200p2217l2m1.img.jpg,"[ Rock Outcrops, Clasts, Rock (Linear Featur..."
3,1p128370308mrd0200p2218l2m1.img.jpg,"[ Rock Outcrops, Rock (Linear Features), Sph..."
4,1p128370471mrd0200p2218l2m1.img.jpg,"[ Soil, Sky]"

In [16]:
train_data.head()

,filename,features
0,1p128287181mrd0000p2303l2m1.img.jpg,"[ Soil, Spherules, Sky, Nearby Surface]"
1,1p128287181mrd0000p2303l2m1.img.jpg_04140167-5...,"[ Soil, Spherules, Sky, Nearby Surface]"
2,1p128287181mrd0000p2303l2m1.img.jpg_175e6765-5...,"[ Soil, Spherules, Sky, Nearby Surface]"
3,1p128287181mrd0000p2303l2m1.img.jpg_196a2c3c-b...,"[ Soil, Spherules, Sky, Nearby Surface]"
4,1p128287181mrd0000p2303l2m1.img.jpg_1bf014ed-f...,"[ Soil, Spherules, Sky, Nearby Surface]"

In [17]:
val_data.head()

,filename,features
0,1p128541565mrd0205p2353l2m1.img.jpg,"[ Rock Outcrops, Rocks (misc), Dunes/Ripples..."
1,1p128541565mrd0205p2353l2m1.img.jpg_01e771ce-6...,"[ Rock Outcrops, Rocks (misc), Dunes/Ripples..."
2,1p128541565mrd0205p2353l2m1.img.jpg_07cf090e-7...,"[ Rock Outcrops, Rocks (misc), Dunes/Ripples..."
3,1p128541565mrd0205p2353l2m1.img.jpg_25254cb3-3...,"[ Rock Outcrops, Rocks (misc), Dunes/Ripples..."
4,1p128541565mrd0205p2353l2m1.img.jpg_2cf88813-9...,"[ Rock Outcrops, Rocks (misc), Dunes/Ripples..."

In [18]:
testshape = test_data.shape
trainshape = train_data.shape
valshape = val_data.shape

print(f"Test shape: {testshape}")
print(f"Train shape: {trainshape}")
print(f"Validation shape: {valshape}")

Test shape: (742, 2)
Train shape: (55986, 2)
Validation shape: (14136, 2)